name: Trader Feedback JS

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_frontend.yml@2.x
    with:
      enable_bundlewatch: false
      enable_prettier: false
      enable_typescript: false

      frontend_directory: ./js
      backend_directory: .
      js_package_manager: yarn
      cache_dependency_path: ./js/yarn.lock

      node_version: 20
      main_git_branch: main
